name: ovolutter
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  awesome_dialog: ^3.2.1
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.0
  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  dots_indicator: ^3.0.0
  dotted_border: ^2.1.0
  equatable: ^2.0.7
  file_picker: ^8.1.4
  firebase_core: ^3.8.0
  firebase_messaging: ^15.1.5
  flutter:
    sdk: flutter
  flutter_inappwebview: ^6.1.5
  flutter_local_notifications: ^18.0.1
  flutter_screenutil: ^5.9.3
  flutter_spinkit: ^5.2.1
  flutter_svg: ^2.0.16
  flutter_widget_from_html: ^0.15.3
  get: ^4.6.6
  google_fonts: ^6.2.1
  google_sign_in: ^6.2.2
  image_gallery_saver_plus: ^3.0.5
  image_picker: ^1.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  lottie: ^3.1.3
  open_file: ^3.5.10
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.3.3
  shimmer: ^3.0.0
  simple_ripple_animation: ^0.1.0
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/images/onboard/
    - assets/images/logo/
    - assets/images/social/
    - assets/images/menu/
    - assets/animation/
    - assets/fonts/

  fonts:
    - family: AlbertSans
      fonts:
        - asset: assets/fonts/Albert_Sans/AlbertSans-Regular.ttf
        - asset: assets/fonts/Albert_Sans/AlbertSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/Albert_Sans/AlbertSans-Italic.ttf
          style: italic
        - asset: assets/fonts/Albert_Sans/AlbertSans-Light.ttf
          weight: 300
    - family: PlayfairDisplay
      fonts:
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: assets/fonts/Playfair_Display/PlayfairDisplay-Italic.ttf
          style: italic
