// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCb6zm7_8kdStXjZMgLZpwjGDuTUg0e_qM',
    appId: '1:274514992002:web:4d77660766f4797500cd9b',
    messagingSenderId: '274514992002',
    projectId: 'flutter-prime-df1c5',
    authDomain: 'flutter-prime-df1c5.firebaseapp.com',
    storageBucket: 'flutter-prime-df1c5.appspot.com',
    measurementId: 'G-KFPM07RXRC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDty_ZTa_aTRiKCpXmJ3_kKQyMPHaRtBKY',
    appId: '1:673830063591:android:c993c55fc142a1e7d0c142',
    messagingSenderId: '673830063591',
    projectId: 'ovolutter',
    storageBucket: 'ovolutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVhtikLkz_kDoHyj_3PbxK-6u0-I_WBmk',
    appId: '1:673830063591:ios:cddff74625310797d0c142',
    messagingSenderId: '673830063591',
    projectId: 'ovolutter',
    storageBucket: 'ovolutter.appspot.com',
    iosBundleId: 'com.example.ovolutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcwfCcKBGvY892deYiQ45soyDbcAL-WW8',
    appId: '1:274514992002:ios:c877669e9834f91d00cd9b',
    messagingSenderId: '274514992002',
    projectId: 'flutter-prime-df1c5',
    storageBucket: 'flutter-prime-df1c5.appspot.com',
    iosBundleId: 'dev.ovolutter.ovolutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCb6zm7_8kdStXjZMgLZpwjGDuTUg0e_qM',
    appId: '1:274514992002:web:d287cbfbfd17977e00cd9b',
    messagingSenderId: '274514992002',
    projectId: 'flutter-prime-df1c5',
    authDomain: 'flutter-prime-df1c5.firebaseapp.com',
    storageBucket: 'flutter-prime-df1c5.appspot.com',
    measurementId: 'G-F7XR5GT999',
  );

}